name: helloworld
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  indexed:

  http: ^0.13.3
  uuid: 
  logger:
  gql_http_link: #[latest-version]
  graphql: ^5.1.1
  json_annotation: ^4.4.0
  flex_color_picker: 
  universal_html: 
  provider: 


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: 
  json_serializable: 

flutter:

  uses-material-design: true
