// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Card struct {
	ID    string  `json:"id"`
	Text  string  `json:"text"`
	X     float64 `json:"x"`
	Y     float64 `json:"y"`
	Color *int    `json:"color"`
}

type CardAddPayload struct {
	ID    string  `json:"id"`
	Text  string  `json:"text"`
	X     float64 `json:"x"`
	Y     float64 `json:"y"`
	Color *int    `json:"color"`
}

type CardMovePayload struct {
	ID string  `json:"id"`
	X  float64 `json:"x"`
	Y  float64 `json:"y"`
}

type CardMutations struct {
	Add    *Card `json:"add"`
	Move   *Card `json:"move"`
	Delete *Card `json:"delete"`
}

type CardQueries struct {
	List []*Card `json:"list"`
}

type DiceMutations struct {
	Set int `json:"set"`
}

type DiceQueries struct {
	Val int `json:"val"`
}
